config/routes.rb
Rails.application.routes.draw do
  root 'recipes#index'
  resources :recipes
  get '/search', to: "recipes#search"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :recipes, dependent: :destroy
  validates :category_name, presence: true, uniqueness: true

  def self.find_or_create(recipe_category_name)
    if recipe_category_name == ""
      recipe_category_name = "Not recognized"
    end
      # Check if that category has already been inserted into categories table, and if it is, then use that existing category_id
      category = Category.find_by category_name: recipe_category_name

      # If category is not present in categories table, then create it
      if !category
        category = Category.create(
          category_name: recipe_category_name
        )
      end
      return category  
  end
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
  belongs_to :recipe
  include PgSearch::Model
  pg_search_scope :search_ingredient, 
                  against: { ingredient_name: 'A' },
                  using: { 
                    tsearch: { 
                      any_word: true,
                      sort_only: false,
                      dictionary: 'english', 
                      tsvector_column: 'searchable' 
                    } 
                  }
end

app/models/recipe.rb
class Recipe < ApplicationRecord
  belongs_to :category
  has_many :ingredients, dependent: :destroy

  def self.find_or_create(recipe_title, recipe_author, recipe_cook_time, recipe_prep_time, recipe_ratings, recipe_image, recipe_category_id, recipe_ingredients)
    recipe_record = Recipe.where(title: recipe_title, author: recipe_author).first

    if recipe_record.nil?
      recipe_record = Recipe.create(
        title:     recipe_title,
        author:    recipe_author,
        cook_time: recipe_cook_time,
        prep_time: recipe_prep_time,
        ratings:   recipe_ratings,
        image:     recipe_image,
        category_id: recipe_category_id
      )
  
      recipe_ingredients.each do |ingredient|
        Ingredient.create(
          recipe_id: recipe_record.id,
          ingredient_name: ingredient
        )
      end
    end  
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  before_action :set_recipe, only: %i[ show ]

  def index
    if params[:category_id]&.present?
      @recipes = Recipe.where(:category_id => params[:category_id] ).order(:title).paginate(page: params[:page], per_page: 26)
    else 
      @recipes = Recipe.order(:title).paginate(page: params[:page], per_page: 26)
    end
  end

  def show
    @recipe = Recipe.find(params[:id])
    @recipes = Recipe.limit(7).order('id desc') #to populate the sidebar
    @ingredients = Ingredient.where(:recipe_id => @recipe.id)
  end

  def search
    if params[:search].blank?
      redirect_to recipes_path and return
    else 
      @parameter = params[:search].downcase
      @recipe_ids = Ingredient.search_ingredient(@parameter).pluck(:recipe_id)
      @results = Recipe.where(id: @recipe_ids).paginate(page: params[:page], per_page: 26)
      #@results = Recipe.joins(:ingredients).search_ingredient(@parameter)
      #@results = Recipe.joins(:ingredients).where("lower(ingredient_name) LIKE :search", search: "%#{@parameter}%" ).distinct.paginate(page: params[:page], per_page: 26)
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_recipe
      @recipe = Recipe.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def recipe_params
      params.require(:recipe).permit(:title, :author, :prep_time, :cook_time, :ratings)
    end  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/recipe_helper.rb
module RecipeHelper
end

app/views/layouts/_alerts.html.erb
<div class="alert alert-warning alert-dismissible fade show" role="alert">
  <%= notice %>
  <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
</div>

app/views/layouts/_footer.html.erb
<div class="container">
  <footer class="d-flex flex-wrap justify-content-between align-items-center py-3 my-4 border-top">
    <div class="col-md-4 d-flex align-items-center">

      <span class="text-muted">&copy; Amir Drljevic</span>
    </div>
  </footer>
</div>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container">
		<%= link_to image_tag("logo.png", alt: "Cookbook logo", width: "200"), root_path%>
    <% link_to 'CookBook', root_path, class:"navbar-brand" %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
				<li class="nav-item">
					<%= form_tag(search_path, :method => "get") do %> 
            <div class="input—group search-box border rounded shadow-sm">
              <%= search_field_tag :search, params[:search], placeholder: "Type an ingredient", class: "form—control" %>             
              <%= button_tag "Search for recipes", class: "btn btn-outline-secondary glyphicon glyphicon—search", :name => nil %>               
            </div>
          <% end %> 
				</li>            	                     
      </ul>

      <ul class="navbar-nav mb-2 mb-lg-0 ">
				<li class="nav-item">
					<%= link_to "Home", root_path, class:"nav-link" %>
				</li>   			
		      <li class="nav-item">
		        <%= link_to "Contact", "#", class:"nav-link" %>
		      </li>   
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
      <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-uWxY/CJNBR+1zjPWmfnSnVxwRheevXITnMqoEIeG1LJrdI0GlVs/9cVSyPYXdcSF" crossorigin="anonymous">
  
    <title>Cookbook</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <br/>    
      <% if notice %>
        <%= render 'layouts/alerts' %>
      <% end %>
      <%= yield %>
    </div>
    <%= render 'layouts/footer' %>
    <!-- Optional JavaScript; choose one of the two! -->

    <!-- Option 1: Bootstrap Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-kQtW33rZJAHjgefvhyyzcGF3C5TFyBQBA13V1RKPf4uH+bwyzQxZ6CmMZHmNBEfJ" crossorigin="anonymous"></script>

    <!-- Option 2: Separate Popper and Bootstrap JS -->
    <!--
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.10.2/dist/umd/popper.min.js" integrity="sha384-7+zCNj/IqJ95wo16oMtfsKbZ9ccEh31eOz1HGyDuCQ6wgnyJNSYdrPa03rtR1zdB" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.2/dist/js/bootstrap.min.js" integrity="sha384-PsUw7Xwds7x08Ew3exXhqzbhuEYmA2xnwc8BuD6SEr+UmEHlX8/MCltYEodzWA4u" crossorigin="anonymous"></script>
    -->
  </body>
</html>

app/views/recipes/index.html.erb
<% if notice %>
  <aside id="notice"><%= notice %></aside>
<% end %>

<h1>Recipes</h1>
<div class="digg_pagination">
  <div class="page_info">
    <%= page_entries_info @recipes %>
  </div>
  <%= will_paginate @recipes, :container => true %>
</div>
<div class="row mb-2">
  <% @recipes.each do |recipe| %>
    <div class="col-md-6">
      <div class="row g-0 border rounded overflow-hidden flex-md-row mb-4 shadow-sm h-md-250 position-relative purple-border">
        <div class="col p-4 d-flex flex-column position-static">
          <strong class="d-inline-block mb-2 text-primary"><%= link_to recipe.category.category_name, recipes_path(category_id: recipe.category_id) %></strong>
          <h3 class="mb-0"><%= link_to recipe.title, recipe_path(recipe.id), class:"no_style_link" %></h3>
          <div class="mb-1 text-muted"><%= "by: " + recipe.author %></div>
          <p class="card-text mb-auto">
            <%= "Prep time: " + recipe.prep_time.to_s + " mins" %></br> 
            <%= "Cook time: " + recipe.cook_time.to_s + " mins" %> </br>
            <%= "Ratings: " + recipe.ratings.to_s %>          
          </p>
          <%= link_to "Continue reading", recipe_path(recipe.id) %>
        </div>
        <div class="col-auto d-none d-lg-block">
          <%= link_to image_tag(recipe.image, class: "recipe_image_thumb"), recipe_path(recipe.id) %>
        </div>
      </div>
    </div>
 <% end %>
</div>
<div class="digg_pagination">
  <%= will_paginate @recipes, :container => true %>
</div>

app/views/recipes/search.html.erb
<% if notice %>
  <aside id="notice"><%= notice %></aside>
<% end %>

<h1>Search results for: <i><%= params[:search] %></i></h1>
<div class="digg_pagination">
  <div class="page_info">
    <%= page_entries_info @results %>
  </div>
  <%= will_paginate @results, :container => true %>
</div>
<div class="row mb-2">
  <% @results.each do |recipe| %>
    <div class="col-md-6">
      <div class="row g-0 border rounded overflow-hidden flex-md-row mb-4 shadow-sm h-md-250 position-relative purple-border">
        <div class="col p-4 d-flex flex-column position-static">
          <strong class="d-inline-block mb-2 text-primary"><%= link_to recipe.category.category_name, recipes_path(category_id: recipe.category_id) %></strong>
          <h3 class="mb-0"><%= link_to recipe.title, recipe_path(recipe.id), class:"no_style_link" %></h3>
          <div class="mb-1 text-muted"><%= "by: " + recipe.author %></div>
          <p class="card-text mb-auto">
            <%= "Prep time: " + recipe.prep_time.to_s + " mins" %></br> 
            <%= "Cook time: " + recipe.cook_time.to_s + " mins" %> </br>
            <%= "Ratings: " + recipe.ratings.to_s %>          
          </p>
          <a href="#" >Continue reading</a>
        </div>
        <div class="col-auto d-none d-lg-block">
          <%= image_tag(recipe.image, class: "recipe_image_thumb") %>
        </div>
      </div>
    </div>
 <% end %>
</div>
<div>
  <% if @results.empty? %>
    <p>Please try with a different ingredient.</p>
  <% end %>
</div>
<div class="digg_pagination">
  <%= will_paginate @results, :container => true %>
</div>

app/views/recipes/show.html.erb
<div class="row g-5">
  <div class="col-md-8">
    <article class="blog-post">
      <h2 class="blog-post-title"><%= @recipe.title %></h2>
      <p class="blog-post-meta"><i><%= "by: " + @recipe.author  %> </i></p>
      <hr>
      <p>
        <%= "Prep time: " + @recipe.prep_time.to_s + " mins" %> </br>
        <%= "Cook time: " + @recipe.cook_time.to_s + " mins" %> </br>
      </p>   
            
      <%= image_tag(@recipe.image, class: "rounded float-end recipe_image_thumb d-block") %>
      
      <div class="p-4 mb-3 bg-light rounded">
        <% @ingredients.each do |ingredient| %>
          <ul>
            <li><%= ingredient.ingredient_name %></li>
          </ul>
        <% end %>
      </div> 
      <%= "Rating: " + @recipe.ratings.to_s %>
      </br>
      Category: <%=  link_to @recipe.category.category_name, recipes_path(category_id: @recipe.category_id) %>
      </br>
    </article>
      </br>
      <%= link_to 'Back', root_path, class: "btn btn-outline-secondary" %>        
  </div>
  <div class="col-md-4">
    <h4>Most recent recipes</h4>
    <% @recipes.each do |post| %>
      <div class="card sidebar_card" style="width: 18rem;">
        <div class="card-body">
          <h5 class="card-title"><%= post.title %></h5>
          <span><i><%= "by: " + post.author %></i> </span></br>
          <%= link_to 'Read recipe', post, class: "btn btn-secondary" %>          
        </div>
      </div>
    <% end %>
  </div>
</div>